[project]
name = "audiobook"
description = "EPUB to audiobook"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "ebooklib>=0.18",
    "kokoro>=0.9.4",
    "misaki>=0.9.4",
    "numpy>=2.0.2",
    "pip>=25.0.1",
    "pymupdf>=1.25.5",
    "soundfile",
    "torch",
    "tqdm>=4.66.5",
]
